# Generated by Django 4.1.13 on 2024-04-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_no', models.CharField(max_length=50)),
                ('mr_no', models.CharField(max_length=50)),
                ('consult_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dept', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('clinician', models.CharField(max_length=50)),
                ('ord_clinician', models.CharField(max_length=50)),
                ('ref_clinician', models.CharField(max_length=50)),
                ('diag_clinic', models.CharField(max_length=50)),
                ('diag_clinician', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('emirated_id', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('passport_id', models.CharField(max_length=50)),
                ('unified', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos')),
                ('full_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('resi_of_emirates', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=20)),
                ('work_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('membership_id', models.CharField(max_length=50)),
                ('additional_info', models.TextField()),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('eligibility_id', models.CharField(max_length=50)),
                ('payer_id', models.CharField(max_length=50)),
            ],
        ),
    ]
