# Generated by Django 4.1.13 on 2024-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
