# Generated by Django 4.1.13 on 2024-03-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0002_appuser_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_password',
        ),
    ]
