# Generated by Django 4.1.13 on 2024-04-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0004_remove_appuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='type_mode',
            new_name='eid',
        ),
        migrations.AddField(
            model_name='appuser',
            name='creation_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='expiry',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='mf_no',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='mode',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
