# Generated by Django 4.1.13 on 2024-04-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0005_rename_type_mode_appuser_eid_appuser_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='attempt',
            new_name='cs_allow',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='contact',
            new_name='session_exp',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='eid',
            new_name='type_mode',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='type',
        ),
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
