# Generated by Django 4.1.13 on 2024-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0006_rename_attempt_appuser_cs_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
