# Generated by Django 4.1.13 on 2024-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0008_alter_appuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
