# Generated by Django 4.1.13 on 2024-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0009_alter_appuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Admin', 'Admin'), ('Nurse', 'Nurse')], max_length=20, null=True),
        ),
    ]
