# Generated by Django 4.1.13 on 2024-05-15 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0012_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Password must contain only letters and numbers', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
