# Generated by Django 4.1.13 on 2024-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0013_alter_appuser_creation_date_alter_appuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
