# Generated by Django 4.1.13 on 2024-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(max_length=50)),
                ('nurse_note', models.CharField(max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
