# Generated by Django 4.1.13 on 2024-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiententry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='nurse_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='nurse_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='nurse_note',
            field=models.TextField(),
        ),
    ]
