# Generated by Django 4.1.13 on 2024-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApieNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=200)),
                ('planning', models.CharField(max_length=200)),
                ('intervention', models.CharField(max_length=200)),
                ('evaluation', models.CharField(max_length=200)),
            ],
        ),
    ]
