# Generated by Django 4.1.13 on 2024-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apienote', '0004_remove_apienote_cid_remove_apienote_nurse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apienote',
            name='mrn',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
