# Generated by Django 4.1.13 on 2024-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseschedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
