# Generated by Django 4.1.13 on 2024-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_schedule', '0002_remove_nurseschedule_duration_nurseschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseschedule',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='mr_no',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='patient_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
