# Generated by Django 4.1.13 on 2024-04-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_schedule', '0003_nurseschedule_address_nurseschedule_mr_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseschedule',
            name='patient_id',
        ),
    ]
