# Generated by Django 4.1.13 on 2024-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_schedule', '0004_remove_nurseschedule_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseschedule',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
