# Generated by Django 4.1.13 on 2024-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_schedule', '0005_alter_nurseschedule_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseschedule',
            name='consult_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurseschedule',
            name='role',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nurseschedule',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
