# Generated by Django 4.1.13 on 2024-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=50)),
                ('mr_no', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
