# Generated by Django 4.1.13 on 2024-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
