# Generated by Django 4.1.13 on 2024-04-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_schedule', '0002_alter_doctorschedule_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='consult_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
