# Generated by Django 4.1.13 on 2024-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=255)),
                ('mrn', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('bmi', models.CharField(max_length=255)),
                ('rbs', models.CharField(max_length=255)),
                ('fbs', models.CharField(max_length=255)),
                ('o2_saturation', models.CharField(max_length=255)),
                ('head_circum', models.CharField(max_length=255)),
                ('chest_circum', models.CharField(max_length=255)),
                ('waist_circum', models.CharField(max_length=255)),
                ('hip_circum', models.CharField(max_length=255)),
                ('abdo_circum', models.CharField(max_length=255)),
                ('pain_score', models.CharField(max_length=255)),
                ('temp_note', models.CharField(max_length=255)),
                ('temp_site', models.CharField(max_length=255)),
                ('pulse_note', models.CharField(max_length=255)),
                ('pulse_site', models.CharField(max_length=255)),
                ('respiration', models.CharField(max_length=255)),
                ('bp_note', models.CharField(max_length=255)),
                ('bp_site', models.CharField(max_length=255)),
            ],
        ),
    ]
