# Generated by Django 4.1.13 on 2024-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsign', '0002_patientvitalsign_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvitalsign',
            name='mrn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
