# Generated by Django 4.1.13 on 2024-04-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsign', '0003_alter_patientvitalsign_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitalsign',
            name='infant',
            field=models.BooleanField(default=False),
        ),
    ]
