# Generated by Django 4.1.13 on 2024-04-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitalsign', '0005_rename_mrn_patientvitalsign_mr_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvitalsign',
            old_name='mr_no',
            new_name='mrn',
        ),
    ]
